### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by barbenhamou** [austanss/skylight#14]
Hi, I have been trying to create an os as an educational challenge, and I have been really struggling with pmm. I have found your os, and tried to copy and adjust your methods but i have a bug. in the pmm_section_manager_create, in the memset part it does an UB - jumps to a random location in the code segment, usually to the reindex. I fu have an idea why that would be great.

**Comment by austanss** [comment]
I am afraid I cannot offer much help in the way of this, because I cannot control the environment your operating system is configuring. Your stack could be too small, your memory layout could be disfigured, or the parameters are corrupt; in any case, this is likely not an issue with this operating system as a whole, but rather an issue with how a portion of this system's code pasted into another project is not guaranteed to work because the conditions are different, and the code was not designed for your operating system's conditions.
